version: '2'
services:
   florentino_store:
     image: 649368968528.dkr.ecr.eu-west-1.amazonaws.com/florentino_store:latest
     ports:
       - "0:3000"
     environment:
       - RAILS_ENV=staging
     hostname: florentino.staging.2bedigital.com
     cpu_shares: 256
     mem_limit: 1G
     command: ./script/start
     logging:
       driver: awslogs
       options:
         awslogs-group: ecs-solidus-staging
         awslogs-region: eu-west-1
         awslogs-stream-prefix: florentino.com
